services:
  - type: web
    name: productivity-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_GENAI_USE_VERTEXAI
        value: FALSE
      - key: MODEL
        value: gemini-2.0-flash
      - key: GOOGLE_API_KEY
        sync: false
